### ISSUE TITLE
Failure when try to pick image from camera

### ISSUE THREAD

**Issue by mukhidinnuridinov** [robertlevonyan/MediaPicker#2]
Hi great project!!))) But I have this failure when try to pick image from camera (Android 4.4)
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=66637, result=-1, data=null} to activity {app.nmn.com.easyappclient/app.nmn.com.easyappclient.activity.RegistrationActivity}: java.lang.IllegalStateException: BitmapFactory.decodeFile…context!!).path, options) must not be null
        at android.app.ActivityThread.deliverResults(ActivityThread.java:3519)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:3562)
        at android.app.ActivityThread.access$1300(ActivityThread.java:155)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1291)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5426)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
        at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.IllegalStateException: BitmapFactory.decodeFile…context!!).path, options) must not be null
        at com.robertlevonyan.components.picker.PickerDialog.takePhoto(PickerDialog.kt:462)
        at com.robertlevonyan.components.picker.PickerDialog.onActivityResult(PickerDialog.kt:445)
        at android.support.v4.app.FragmentActivity.onActivityResult(FragmentActivity.java:156)
        at android.app.Activity.dispatchActivityResult(Activity.java:5488)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:3515)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:3562) 
        at android.app.ActivityThread.access$1300(ActivityThread.java:155) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1291) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.app.ActivityThread.main(ActivityThread.java:5426) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084) 
        at dalvik.system.NativeStart.main(Native Method) 
How can I solve this?

**Comment by robertlevonyan** [comment]
where is created your dialog. In activity or fragment?

**Comment by robertlevonyan** [comment]
Try the new version (1.1.2)
